project_id = "ubhonbarxxvvqichlkjw"

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
enable_signup = false

[functions.admin-create-user]
verify_jwt = true

[functions.sync-project-github]
verify_jwt = true

[functions.delete-record]
verify_jwt = true
