-- No-op: this migration was an exact duplicate of
-- 20260831080340_e3636d49-0501-4b1f-ae5f-7888ea86a4f8.sql, which runs earlier
-- and already creates admin_audit_log, its indexes, policies, audit trigger
-- functions and permission seed rows.
--
-- Replaying both in order failed with:
--   ERROR: relation "admin_audit_log" already exists (SQLSTATE 42P07)
-- which broke `supabase db reset` from a clean database.
--
-- Version 20260831120000 is already recorded as applied in every environment,
-- so this file is kept (not deleted) to preserve migration history, with its
-- body removed to make a clean replay succeed.
