-- This migration was published as an exact duplicate of
-- 20260830120000_mining_operations_vertical_slice.sql.
--
-- Keep the version file so environments that already recorded it remain in
-- sync, but do not replay the same CREATE TABLE and CREATE POLICY statements
-- during a fresh local reset.
